### ISSUE TITLE
Pacakge request: <miredo>

### ISSUE THREAD

**Issue by buzhangsan** [Entware-ng/merge#1]
Pacakge request:
link：https://www.remlab.net/miredo
for mipsel
‘’6in4‘’ need public network IP(we call it ‘’公网ip‘’)，but I dont have。
so I wish it，thinks a lot if I can get it。

**Comment by ryzhovau** [comment]
https://github.com/Entware/entware#entware-ng-3x-and-entware-ng-merged-to-become-entware

**Comment by ryzhovau** [comment]
https://github.com/Entware/Entware/issues/32
